version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
  document-service:
    build:
      context: .
      dockerfile: document-service/Dockerfile
    depends_on:
      - mongodb

  tenant-service:
    build:
      context: .
      dockerfile: tenant-service/Dockerfile
    depends_on:
      - mongodb

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    depends_on:
      - document-service
      - tenant-service

volumes:
  mongodb_data: